### ISSUE TITLE
Exploring Hidden Markov Models site disappeared 

### ISSUE THREAD

**Issue by angushushu** [nipunbatra/nipunbatra.github.io#1]
Dear professor Batra, I was learning Hidden Markov Models through your interactive site https://nipunbatra.github.io/hmm/. However, there is a 404 error when I access the site today. May I ask if the page will be back? It is a very clear introduction article. Thank you very much!

**Comment by nipunbatra** [comment]
@angushushu 

My Github Pro expired and thus the private page is not building. 

It should hopefully be up soon.

In the meantime, I have made the repo public https://github.com/nipunbatra/hmm

**Comment by angushushu** [comment]
> @angushushu 
> 
> My Github Pro expired and thus the private page is not building. 
> 
> It should hopefully be up soon.
> 
> In the meantime, I have made the repo public https://github.com/nipunbatra/hmm

I understand. Thank you for replying and share the repo! Very helpful!

**Comment by nipunbatra** [comment]
It's up and running now at https://nipunbatra.github.io/hmm/
